#' Plots a graph that shows the effect of several features over multiple observations.
#' @description This method draws a plot for, the observed value and describes
#'   the influence of the selected features.
#' @param shap.values A shapley object (generated by shapley(...)) that contains
#' the shapley.values and other important information about the task and model.
#' @param features A vector of the interesting feature names.
#' @export
plot.shapley.multipleFeatures = function(shap.values, features = c("crim", "lstat")) {
  features.values = getShapleyValues(shap.values)[,features]
  features.numbers = ncol(features.values)

  data = data.frame(matrix(data = 0, nrow = nrow(getShapleyValues(shap.values)), ncol = 1 + features.numbers))
  names(data) = c(names(features.values), "position")
  data[,names(features.values)] = features.values
  data$position = as.numeric(getShapleyIds(shap.values))
  plot.data = melt(data, id.vars = "position")

  plot = ggplot(plot.data) +
    geom_line(aes(x = position, y = value, group = variable, color = variable))

  return(plot)
}
